-- Initial data for compositions table
-- Representative works of famous classical composers (~20 works each)

SET NAMES utf8mb4;

-- Johann Sebastian Bach (id=1)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(1, 'BWV 1046', 'Brandenburg Concerto No. 1 in F major'),
(1, 'BWV 1047', 'Brandenburg Concerto No. 2 in F major'),
(1, 'BWV 1048', 'Brandenburg Concerto No. 3 in G major'),
(1, 'BWV 1049', 'Brandenburg Concerto No. 4 in G major'),
(1, 'BWV 1050', 'Brandenburg Concerto No. 5 in D major'),
(1, 'BWV 1051', 'Brandenburg Concerto No. 6 in B-flat major'),
(1, 'BWV 1041', 'Violin Concerto in A minor'),
(1, 'BWV 1042', 'Violin Concerto in E major'),
(1, 'BWV 1043', 'Concerto for Two Violins in D minor'),
(1, 'BWV 988', 'Goldberg Variations'),
(1, 'BWV 244', 'St Matthew Passion'),
(1, 'BWV 245', 'St John Passion'),
(1, 'BWV 232', 'Mass in B minor'),
(1, 'BWV 1079', 'Musical Offering'),
(1, 'BWV 1080', 'The Art of Fugue'),
(1, 'BWV 846-869', 'The Well-Tempered Clavier, Book I'),
(1, 'BWV 870-893', 'The Well-Tempered Clavier, Book II'),
(1, 'BWV 582', 'Passacaglia and Fugue in C minor'),
(1, 'BWV 565', 'Toccata and Fugue in D minor'),
(1, 'BWV 140', 'Wachet auf, ruft uns die Stimme');

-- Antonio Vivaldi (id=2)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(2, 'RV 269', 'The Four Seasons: Spring'),
(2, 'RV 315', 'The Four Seasons: Summer'),
(2, 'RV 293', 'The Four Seasons: Autumn'),
(2, 'RV 297', 'The Four Seasons: Winter'),
(2, 'RV 356', 'Violin Concerto in G minor'),
(2, 'RV 230', 'Violin Concerto in D major "Grosso Mogul"'),
(2, 'RV 580', 'Concerto for 4 Violins in B minor'),
(2, 'RV 425', 'Guitar Concerto in D major'),
(2, 'RV 439', 'Concerto for 2 Mandolins in G major'),
(2, 'RV 103', 'Concerto for 2 Trumpets in C major'),
(2, 'RV 443', 'Piccolo Concerto in C major'),
(2, 'RV 428', 'Concerto for 2 Cellos in G minor'),
(2, 'RV 522', 'Concerto for 2 Oboes in D minor'),
(2, 'RV 565', 'Concerto for Strings in G major "Alla rustica"'),
(2, 'RV 158', 'Concerto Grosso in D minor'),
(2, 'RV 589', 'Gloria in D major'),
(2, 'RV 608', 'Magnificat in G minor'),
(2, 'RV 596', 'Concerto in D minor (after J.S. Bach BWV 596)'),
(2, 'RV 169', 'Concerto for Flute in F major "La tempesta di mare"'),
(2, 'RV 90', 'Concerto for Flute in D major "Il gardellino"');

-- George Frideric Handel (id=3)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(3, 'HWV 56', 'Messiah'),
(3, 'HWV 351', 'Water Music Suite No. 1 in F major'),
(3, 'HWV 349', 'Music for the Royal Fireworks'),
(3, 'HWV 19', 'Giulio Cesare'),
(3, 'HWV 17', 'Rinaldo'),
(3, 'HWV 7a', 'Alcina'),
(3, 'HWV 34', 'Ariodante'),
(3, 'HWV 50a', 'Esther'),
(3, 'HWV 52', 'Athalia'),
(3, 'HWV 53', 'Saul'),
(3, 'HWV 54', 'Israel in Egypt'),
(3, 'HWV 57', 'Samson'),
(3, 'HWV 67', 'Judas Maccabaeus'),
(3, 'HWV 76', 'Joshua'),
(3, 'HWV 289', 'Dixit Dominus'),
(3, 'HWV 430', 'Keyboard Suite No. 5 in E major "Harmonious Blacksmith"'),
(3, 'HWV 296', 'Zadok the Priest'),
(3, 'HWV 287', 'Coronation Anthem "The King shall rejoice"'),
(3, 'HWV 295', 'Ode for St Cecilia\'s Day'),
(3, 'HWV 55', 'L\'Allegro, il Penseroso ed il Moderato');

-- Ludwig van Beethoven (id=4)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(4, 'Op. 21', 'Symphony No. 1 in C major'),
(4, 'Op. 36', 'Symphony No. 2 in D major'),
(4, 'Op. 55', 'Symphony No. 3 in E-flat major "Eroica"'),
(4, 'Op. 60', 'Symphony No. 4 in B-flat major'),
(4, 'Op. 67', 'Symphony No. 5 in C minor'),
(4, 'Op. 68', 'Symphony No. 6 in F major "Pastoral"'),
(4, 'Op. 92', 'Symphony No. 7 in A major'),
(4, 'Op. 93', 'Symphony No. 8 in F major'),
(4, 'Op. 125', 'Symphony No. 9 in D minor "Choral"'),
(4, 'Op. 61', 'Violin Concerto in D major'),
(4, 'Op. 15', 'Piano Concerto No. 1 in C major'),
(4, 'Op. 19', 'Piano Concerto No. 2 in B-flat major'),
(4, 'Op. 37', 'Piano Concerto No. 3 in C minor'),
(4, 'Op. 58', 'Piano Concerto No. 4 in G major'),
(4, 'Op. 73', 'Piano Concerto No. 5 in E-flat major "Emperor"'),
(4, 'Op. 27 No. 2', 'Piano Sonata No. 14 in C-sharp minor "Moonlight"'),
(4, 'Op. 13', 'Piano Sonata No. 8 in C minor "Pathétique"'),
(4, 'Op. 57', 'Piano Sonata No. 23 in F minor "Appassionata"'),
(4, 'Op. 106', 'Piano Sonata No. 29 in B-flat major "Hammerklavier"'),
(4, 'WoO 59', 'Für Elise');

-- Wolfgang Amadeus Mozart (id=5)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(5, 'K. 525', 'Eine kleine Nachtmusik'),
(5, 'K. 551', 'Symphony No. 41 in C major "Jupiter"'),
(5, 'K. 550', 'Symphony No. 40 in G minor'),
(5, 'K. 543', 'Symphony No. 39 in E-flat major'),
(5, 'K. 504', 'Symphony No. 38 in D major "Prague"'),
(5, 'K. 385', 'Symphony No. 35 in D major "Haffner"'),
(5, 'K. 297', 'Symphony No. 31 in D major "Paris"'),
(5, 'K. 622', 'Clarinet Concerto in A major'),
(5, 'K. 466', 'Piano Concerto No. 20 in D minor'),
(5, 'K. 467', 'Piano Concerto No. 21 in C major'),
(5, 'K. 491', 'Piano Concerto No. 24 in C minor'),
(5, 'K. 595', 'Piano Concerto No. 27 in B-flat major'),
(5, 'K. 492', 'Le nozze di Figaro'),
(5, 'K. 527', 'Don Giovanni'),
(5, 'K. 620', 'Die Zauberflöte'),
(5, 'K. 588', 'Così fan tutte'),
(5, 'K. 626', 'Requiem in D minor'),
(5, 'K. 387', 'String Quartet No. 14 in G major'),
(5, 'K. 331', 'Piano Sonata No. 11 in A major "Turkish March"'),
(5, 'K. 545', 'Piano Sonata No. 16 in C major');

-- Franz Schubert (id=6)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(6, 'D. 944', 'Symphony No. 9 in C major "Great"'),
(6, 'D. 759', 'Symphony No. 8 in B minor "Unfinished"'),
(6, 'D. 956', 'String Quintet in C major'),
(6, 'D. 810', 'String Quartet No. 14 in D minor "Death and the Maiden"'),
(6, 'D. 667', 'Piano Quintet in A major "Trout"'),
(6, 'D. 887', 'Piano Trio No. 2 in E-flat major'),
(6, 'D. 898', 'String Quartet No. 15 in G major'),
(6, 'D. 960', 'Piano Sonata No. 21 in B-flat major'),
(6, 'D. 958', 'Piano Sonata No. 19 in C minor'),
(6, 'D. 959', 'Piano Sonata No. 20 in A major'),
(6, 'D. 899', 'Impromptus Op. 90'),
(6, 'D. 935', 'Impromptus Op. 142'),
(6, 'D. 780', 'Moments Musicaux'),
(6, 'D. 934', 'Fantasy in C major for Violin and Piano'),
(6, 'D. 821', 'Arpeggione Sonata'),
(6, 'D. 778', 'Wanderer Fantasy'),
(6, 'D. 911', 'Winterreise'),
(6, 'D. 795', 'Die schöne Müllerin'),
(6, 'D. 957', 'Schwanengesang'),
(6, 'D. 797', 'Rosamunde Overture');

-- Frédéric Chopin (id=7)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(7, 'Op. 9', 'Nocturnes Op. 9'),
(7, 'Op. 27', 'Nocturnes Op. 27'),
(7, 'Op. 48', 'Nocturnes Op. 48'),
(7, 'Op. 55', 'Nocturnes Op. 55'),
(7, 'Op. 10', 'Études Op. 10'),
(7, 'Op. 25', 'Études Op. 25'),
(7, 'Op. 28', '24 Preludes'),
(7, 'Op. 64', 'Waltzes Op. 64'),
(7, 'Op. 18', 'Grande Valse Brillante'),
(7, 'Op. 53', 'Polonaise in A-flat major "Heroic"'),
(7, 'Op. 40 No. 1', 'Polonaise in A major "Military"'),
(7, 'Op. 26 No. 2', 'Polonaise in E-flat minor'),
(7, 'Op. 35', 'Piano Sonata No. 2 in B-flat minor "Funeral March"'),
(7, 'Op. 58', 'Piano Sonata No. 3 in B minor'),
(7, 'Op. 21', 'Piano Concerto No. 2 in F minor'),
(7, 'Op. 11', 'Piano Concerto No. 1 in E minor'),
(7, 'Op. 54', 'Scherzo No. 4 in E major'),
(7, 'Op. 20', 'Scherzo No. 1 in B minor'),
(7, 'Op. 51', 'Ballade No. 4 in F minor'),
(7, 'Op. 23', 'Ballade No. 1 in G minor');

-- Johannes Brahms (id=8)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(8, 'Op. 68', 'Symphony No. 1 in C minor'),
(8, 'Op. 73', 'Symphony No. 2 in D major'),
(8, 'Op. 90', 'Symphony No. 3 in F major'),
(8, 'Op. 98', 'Symphony No. 4 in E minor'),
(8, 'Op. 15', 'Piano Concerto No. 1 in D minor'),
(8, 'Op. 83', 'Piano Concerto No. 2 in B-flat major'),
(8, 'Op. 77', 'Violin Concerto in D major'),
(8, 'Op. 102', 'Double Concerto for Violin and Cello'),
(8, 'Op. 45', 'Ein deutsches Requiem'),
(8, 'Op. 56a', 'Variations on a Theme by Haydn'),
(8, 'Op. 51 No. 1', 'String Quartet No. 1 in C minor'),
(8, 'Op. 51 No. 2', 'String Quartet No. 2 in A minor'),
(8, 'Op. 67', 'String Quartet No. 3 in B-flat major'),
(8, 'Op. 111', 'String Quintet in G major'),
(8, 'Op. 115', 'Clarinet Quintet in B minor'),
(8, 'Op. 118', 'Six Piano Pieces'),
(8, 'Op. 119', 'Four Piano Pieces'),
(8, 'Op. 117', 'Three Intermezzos'),
(8, 'Op. 79', 'Two Rhapsodies'),
(8, 'Op. 39', 'Waltzes Op. 39');

-- Felix Mendelssohn (id=9)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(9, 'Op. 21', 'Overture "A Midsummer Night\'s Dream"'),
(9, 'Op. 61', 'Incidental Music to "A Midsummer Night\'s Dream"'),
(9, 'Op. 26', 'Hebrides Overture "Fingal\'s Cave"'),
(9, 'Op. 90', 'Symphony No. 3 in A minor "Scottish"'),
(9, 'Op. 56', 'Symphony No. 4 in A major "Italian"'),
(9, 'Op. 107', 'Symphony No. 5 in D major "Reformation"'),
(9, 'Op. 64', 'Violin Concerto in E minor'),
(9, 'Op. 25', 'Piano Concerto No. 1 in G minor'),
(9, 'Op. 40', 'Piano Concerto No. 2 in D minor'),
(9, 'Op. 36', 'Oratorio "St. Paul"'),
(9, 'Op. 70', 'Oratorio "Elijah"'),
(9, 'Op. 20', 'Octet for Strings in E-flat major'),
(9, 'Op. 44', 'String Quartets Op. 44'),
(9, 'Op. 13', 'String Quartet No. 2 in A minor'),
(9, 'Op. 62', 'Songs Without Words Book 5'),
(9, 'Op. 67', 'Songs Without Words Book 6'),
(9, 'Op. 19', 'Songs Without Words Book 1'),
(9, 'Op. 30', 'Songs Without Words Book 2'),
(9, 'Op. 38', 'Songs Without Words Book 3'),
(9, 'Op. 53', 'Songs Without Words Book 4');

-- Pyotr Ilyich Tchaikovsky (id=10)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(10, 'Op. 74', 'Symphony No. 6 in B minor "Pathétique"'),
(10, 'Op. 64', 'Symphony No. 5 in E minor'),
(10, 'Op. 36', 'Symphony No. 4 in F minor'),
(10, 'Op. 71', 'The Nutcracker'),
(10, 'Op. 66', 'Swan Lake'),
(10, 'Op. 20', 'Sleeping Beauty'),
(10, 'Op. 49', 'Overture "1812"'),
(10, 'Op. 32', 'Romeo and Juliet Fantasy Overture'),
(10, 'Op. 35', 'Violin Concerto in D major'),
(10, 'Op. 23', 'Piano Concerto No. 1 in B-flat minor'),
(10, 'Op. 44', 'Piano Concerto No. 2 in G major'),
(10, 'Op. 62', 'Serenade for Strings in C major'),
(10, 'Op. 11', 'String Quartet No. 1 in D major'),
(10, 'Op. 33', 'Variations on a Rococo Theme'),
(10, 'Op. 31', 'Capriccio Italien'),
(10, 'Op. 18', 'The Tempest'),
(10, 'TH 30', 'Marche Slave'),
(10, 'TH 42', 'Eugene Onegin'),
(10, 'TH 68', 'The Queen of Spades'),
(10, 'Op. 37a', 'The Seasons');

-- Sergei Rachmaninoff (id=11)
INSERT INTO compositions (composer_id, catalog_number, title) VALUES
(11, 'Op. 18', 'Piano Concerto No. 2 in C minor'),
(11, 'Op. 30', 'Piano Concerto No. 3 in D minor'),
(11, 'Op. 40', 'Piano Concerto No. 4 in G minor'),
(11, 'Op. 43', 'Rhapsody on a Theme of Paganini'),
(11, 'Op. 13', 'Symphony No. 1 in D minor'),
(11, 'Op. 27', 'Symphony No. 2 in E minor'),
(11, 'Op. 44', 'Symphony No. 3 in A minor'),
(11, 'Op. 45', 'Symphonic Dances'),
(11, 'Op. 29', 'The Bells'),
(11, 'Op. 1', 'Piano Concerto No. 1 in F-sharp minor'),
(11, 'Op. 3 No. 2', 'Prelude in C-sharp minor'),
(11, 'Op. 23', 'Ten Preludes'),
(11, 'Op. 32', 'Thirteen Preludes'),
(11, 'Op. 33', 'Études-Tableaux Op. 33'),
(11, 'Op. 39', 'Études-Tableaux Op. 39'),
(11, 'Op. 17', 'Suite No. 1 for Two Pianos'),
(11, 'Op. 5', 'Suite No. 2 for Two Pianos'),
(11, 'Op. 28', 'Piano Sonata No. 1 in D minor'),
(11, 'Op. 36', 'Piano Sonata No. 2 in B-flat minor'),
(11, 'Op. 34', 'Vocalise');
